---
name: Test

"on":
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@v3.0.0
