---
name: Update Dependencies

"on":
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Get token
        id: get-token
        # yamllint disable-line rule:line-length
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db # v2.1.0
        with:
          application_id: ${{ secrets.AKI_BOT_APP_ID }}
          application_private_key: ${{ secrets.AKI_BOT_APP_PRIVATE_KEY }}
          permissions: >
            contents:write,
            issues:write,
            pull_requests:write,
            workflows:write

      - name: Update dependencies
        # yamllint disable-line rule:line-length
        uses: renovatebot/github-action@f9c81dddc9b589e4e6ae0326d1e36f6bc415d230 # v39.2.4
        with:
          renovate-version: 37.116.0
          configurationFile: renovate.json5
          token: x-access-token:${{ steps.get-token.outputs.token }}
        env:
          LOG_LEVEL: debug
