name: Workflow to simulate renovate updates

"on":
  workflow_dispatch:

jobs:
  stub:
    name: Stub
    runs-on: ubuntu-latest

    steps:
      - name: Action with major.minor.patch
        # yamllint disable-line rule:line-length
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Action with major.minor
        # yamllint disable-line rule:line-length
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Action with major
        # yamllint disable-line rule:line-length
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Action that uses java version
        # yamllint disable-line rule:line-length
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          distribution: temurin
          # renovate: datasource=adoptium-java depName=java
          java-version: 17.0.8+101

      - name: Action that uses python version
        # yamllint disable-line rule:line-length
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          # renovate: datasource=docker depName=python versioning=docker
          python-version: 3.12.0
          cache: pip
