name: Workflow to simulate renovate updates

"on":
  workflow_dispatch:

jobs:
  stub:
    name: Stub
    runs-on: ubuntu-latest

    steps:
      - name: Action with major.minor.patch
        # yamllint disable-line rule:line-length
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Action with major.minor
        # yamllint disable-line rule:line-length
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Action with major
        # yamllint disable-line rule:line-length
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Action that uses java version
        # yamllint disable-line rule:line-length
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          distribution: temurin
          java-version: 17.0.11+9

      - name: Show Java version
        run: java --version

      - name: Action that uses python version
        # yamllint disable-line rule:line-length
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: 3.12.3
          cache: pip

      - name: Show Python version
        run: python --version

      - name: Action that uses just
        # yamllint disable-line rule:line-length
        uses: extractions/setup-just@69d82fb0233557aec017ef13706851d0694e0f1d # v1.6.0
        with:
          just-version: 1.27.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show just version
        run: just --version
