name: Workflow to simulate renovate updates

"on":
  workflow_dispatch:

jobs:
  stub:
    name: Stub
    runs-on: ubuntu-latest

    steps:
      - name: Action with major.minor.patch
        # yamllint disable-line rule:line-length
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Action with major.minor
        # yamllint disable-line rule:line-length
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Action with major
        # yamllint disable-line rule:line-length
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Action that uses java version
        # yamllint disable-line rule:line-length
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
        with:
          distribution: temurin
          # renovate: datasource=adoptium-java depName=java
          java-version: 17.0.8+101

      - name: Action that uses python version
        # yamllint disable-line rule:line-length
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          # renovate: datasource=docker depName=python versioning=docker
          python-version: 3.12.0
          cache: pip
