---
name: Write File

"on":
  workflow_dispatch:

jobs:
  write-file:
    name: Update dependencies
    runs-on: self-hosted

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0

      - name: Write file
        run: echo "$(date)" > file.txt
